app/urls.py
from django.urls import re_path
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    re_path(r'^$', login_required(views.MessangerView.as_view(), login_url='/auth/'), name="index"),
    re_path(r'^auth/$', views.AuthenticationView.as_view(), name="auth"),
    re_path(r'^check_user_account/', views.CheckUserAccountView.as_view()),
    re_path(r'^register_user/', views.RegisterUserView.as_view()),
    re_path(r'^login_user/', views.LoginUserView.as_view()),
    re_path(r'^(?P<chat_id>\d+)/$', login_required(views.ChatView.as_view()), name="chat"),
    re_path(r'send_code/', views.SendEmailView.as_view()),
    re_path(r"^search_users/", login_required(views.PeopleSearchView.as_view())),
    re_path(r"^create_new_chat/(?P<user_id>\d+)", login_required(views.CreateChatView.as_view())),
    re_path(r"^make_reaction_on_message/", login_required(views.MakeReactionView.as_view())),
    re_path(r"^logout/", login_required(views.LogoutView.as_view()), name="logout"),
    re_path(r"^update_data/", login_required(views.UpdateDataView.as_view()), name="update"),
]

app/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models
from django.utils import timezone


class CustomUserManager(BaseUserManager):
    """
    This is Custom Manager for Custom User,
    used for create new interface for creating Custom User
    """

    def create_user(self, email: str, first_name: str, last_name: str, account_name=None,
                    **extra_fields) -> 'CustomUser':
        """
        Used for create Custom User using custom fields
        :param email: user email
        :param first_name: first name of user
        :param last_name: last name of user
        :param account_name: short account name , for easier searching
        :param extra_fields: something extra
        :return: instance of Custom User class
        """

        if not email:
            raise ValueError('The Email field must be set')
        if account_name and not account_name.startswith('@'):
            account_name = '@' + account_name
        user = self.model(
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
            account_name=account_name,
            **extra_fields
        )
        user.save(using=self._db)
        return user


class CustomUser(AbstractBaseUser):
    """
    Database model for custom users.
    Save all info about user account
    """

    user_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    account_name = models.CharField(max_length=50, unique=True, null=True,blank=True)
    email = models.EmailField(unique=True)
    photo = models.ImageField(upload_to='', blank=True, null=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD = 'account_name'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['email', 'first_name', 'last_name']

    def __str__(self):
        return self.account_name or f"{self.first_name} {self.last_name}"


class Message(models.Model):
    """
    Database model for messages.
    Save all information about message user,
    message text , date and time of sending
    """

    message_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    text = models.CharField(max_length=512)
    date_of_sending = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Message {self.message_id} from {self.user}'

    @staticmethod
    def create(user: 'CustomUser', text: str) -> 'Message':
        """
        This method create and save message,
        that user was wrote
        :param user: instance of CustomUser
        :param text: string with message
        :return: instance of Message
        """

        message = Message.objects.create(user=user, text=text, date_of_sending=timezone.now())

        message.save()

        return message


class Chat(models.Model):
    """
    Database model for chats.
    Save information about chat users and all messages
    """

    chat_id = models.AutoField(primary_key=True)
    users = models.ManyToManyField(CustomUser)
    messages = models.ManyToManyField(Message)

    @staticmethod
    def get_sorted_chats(user):
        chats = Chat.objects.filter(users=user) \
            .annotate(last_message_date=models.Max('messages__date_of_sending')) \
            .order_by(models.F('last_message_date').desc(nulls_last=True))

        return chats

    # @property
    # def last_message_date(self):
    #     return self.messages.aggregate(models.Max('date_of_sending')).get('date_of_sending__max')

    def __str__(self):
        return f'Chat {self.chat_id}'

    @staticmethod
    def create(user_1: 'CustomUser', user_2: 'CustomUser') -> 'Chat':
        """
        This method based on Multiton pattern.
        If chat with given users is exist return that,
        If not create new, and return
        :param: user_1: instance of CustomUser
        :param: user_2: instance of CustomUser
        :return: instance of Chat
        """

        existing_chat = Chat.objects.filter(users= user_1).filter(users= user_2).first()

        if not existing_chat:
            existing_chat = Chat.objects.create()

            existing_chat.users.add(user_1, user_2)

            existing_chat.save()

        return existing_chat

    def get_second_user(self, first_user: 'CustomUser') -> 'CustomUser':
        """
        Take user, check all users in current chat,and return second user
        :param first_user: user who open main page
        :return: CustomUser
        """
        users = self.users.all()

        for user in users:
            if user.user_id != first_user.user_id:
                return user


class Reaction(models.Model):
    """
    Database model for reactions.
    Save all information about user,who react on message,
    what message and name of reaction
    """

    reaction_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    message = models.ForeignKey(Message, on_delete=models.CASCADE)
    name_of_reaction = models.CharField(max_length=50, default='like')

    def __str__(self):
        return f'{self.user} reacted with {self.name_of_reaction} to message {self.message}'

    @staticmethod
    def create(user: 'CustomUser', message: 'Message') -> 'None':
        """
        This method create reaction on message
        :param user: instance of CustomUser
        :param message: instance of Message
        :return: None
        """

        reaction = Reaction.objects.create(user=user, message=message)

        reaction.save()

templates/main/chat.html
{% extends 'main/index.html' %}
{% load static %}

{% block chat %}
<div class="correspondence__user h-100">
          <div class="correspondence__user-info">
            <p class="correspondence__user-name user-name">{{ second_user.first_name }} {{ second_user.last_name }}</p>
            <p class="correspondence__user-status">{% if second_user.is_active %} online {% else %} offline {% endif %}</p>
          </div>
          <img src="{% static 'images/phone.svg' %}" alt="btn for phone call" class="correspondence__phone-img">
          <img src="{% static 'images/camera.svg' %}" alt="btn for video call" class="correspondence__camera-img">
        </div>
        <div class="correspondence__message">
          {% if messages_by_day %}
            {% for messages in messages_by_day %}
            <div class="correspondence__message-box messages">
              <p class="messages__time">{{ messages.0.date_of_sending|date:'j.m'}}</p>
              {% for message in messages %}
                  {% if message.user.user_id == user.user_id %}
                      <p  ondblclick="makeReaction(this, {{message.message_id}},{{request.user.user_id}}, 'left')" class="messages__curent-user user-massage
                      {% if message.reaction_set.exists%} like-message like-left {% endif %}">
                          {{ message.text }}
                      </p>
                  {% else %}
                      <p ondblclick="makeReaction(this, {{message.message_id}},{{request.user.user_id}}, 'right')" class="messages__other-user user-massage
                       {% if message.reaction_set.exists%} like-message like-right {% endif %}">
                          {{ message.text }}
                      </p>
                  {% endif %}
              {% endfor %}
            </div>
            {% endfor %}
          {% else %}
            <p id="chat__nomessages">Поки що повідомлень немає</p>
          {% endif %}
          <div id="new__messages" class="correspondence__message-box messages">

          </div>
          <form class="correspondence__input-box h-100">
            <input autocomplete="off" id="chat__message" class="correspondence__input" type="text" name="message" placeholder="Напишіть повідомлення...">
            <button id="chat__sendbutton" class="correspondence__input-btn" type="submit">
              <img class="correspondence__input-img" src="{% static 'images/send.png' %}" alt="">
            </button>
          </form>
        </div>
{% endblock %}

templates/main/index.html
<!DOCTYPE html>
<html lang="uk">
{% load static %}

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>

  <!-- google fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans&family=Roboto&display=swap" rel="stylesheet">

  <!-- css style -->
  <link rel="stylesheet" href="{% static 'css/main_style.css' %}">

  <script src="{% static 'js/axios.min.js' %}"></script>
  <script src="{% static 'js/script.js' %}" defer></script>

</head>

<body>
  <div class="settings-box">
    <form class="settings-form" action="{% url 'update' %}", method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <input type="hidden" name="url" value="{{request.path}}">
      <label class="settings-lable lable-photo" for="settings_photo" >
        <img class="setting-photo"
        {% if request.user.photo %}
           src="{% get_media_prefix %}{{request.user.photo}}"
        {% else %}
           src = "{% static 'images/user.png' %}"
        {% endif %}
     alt="photo-user">
        <div class="setting-photo__text"><p>Додати фото</p></div>
      </label>
      <input id="settings_photo" autocomplete="off" name="photo" class="settings-input" type="file">
      <div class="settings-box__inner">
        <label class="settings-lable" for="settings_fname">Ім'я</label>
        <input id="settings_fname" name="first_name" class="settings-input" type="text" autocomplete="off" value="{{request.user.first_name}}">
      </div>
      <div class="settings-box__inner">
        <label class="settings-lable" for="settings_lname">Прізвище</label>
        <input id="settings_lname" name="last_name" class="settings-input" type="text" autocomplete="off" value="{{request.user.last_name}}">
      </div>
      <label class="settings-lable" for="settings_account_name">Нікнейм</label>
      <input id="settings_account_name" name="account_name" class="settings-input" autocomplete="off" type="text"
         {% if request.user.account_name %}
            value ="{{request.user.account_name}}"
         {% endif %}
      >
      <button class="settings-btn">Зберегти</button>
      <div id="close-form" class="close-form">
        <span></span>
      </div>
    </form>


    <form action="{% url 'logout' %}" method="POST">
      {% csrf_token %}
      <button class="settings-btn">Вийти</button>
    </form>
  </div>

  <main class="chats__wrapper" style="background-image: url({% static 'images/chat-bg.svg' %});">
    <div class="chats">

      <div class="chats__sidebar sidebar">
        <div class="sidebar__top current-user h-100">
          <img
            {% if request.user.photo %}
              src="{% get_media_prefix %}{{request.user.photo}}"
            {% else %}
              src = "{% static 'images/user.png' %}"
            {% endif %}
          alt="Current user photo" class="current-user__img">
          <p class="current-user__name user-name">{{ user.first_name}} {{ user.last_name}}</p>
          <img src="{% static 'images/search.svg' %}" alt="search icon" class="search">
          <img src="{% static 'images/setting.svg' %}" alt="setting icon" class="setting">
          {% csrf_token %}
          <div class="search-people">
            <input class="search-people__input" type="text" placeholder="Пошук..." readonly autocomplete="off">
              <div class="search-people__inner">
                <ul id="search-people-list" class="search-people__list">
                </ul>
              </div>
          </div>
        </div>

        <div class="sidebar__list list-chats">
          <ul id="chat__list" class="chats__list">
            {% for chat in chats %}
            <li class="chats__item">
              <a id="chat__{{ chat.chat_id }}" href="/{{chat.chat_id}}" class="chats__link">
                <img
                  {% if chat.user.photo %}
                    src="{% get_media_prefix %}{{chat.user.photo}}"
                  {% else %}
                    src = "{% static 'images/user.png' %}"
                  {% endif %}
                alt="user photo" class="chats__user-img">
                <div class="chats__text">
                  <p class="chats__user-name user-name">{{ chat.user.first_name }} {{ chat.user.last_name }}</p>
                  <p class="chats__user-message">{{ chat.last_message }}</p>
                </div>
                <div class="chats__notification notification-active">
                </div>
              </a>
            </li>
            {% empty %}
            <p>У вас,поки,немає чатів...</p>
            {% endfor %}
          </ul>
        </div>

      </div>

      <div id="main__chat" class="chats__correspondence correspondence">
        {% block chat %}<p class="main__chat-notification">Для початку - оберіть чат...</p>{% endblock %}
      </div>

    </div>
  </main>

</body>

</html>